### ISSUE TITLE
MGM bitmask- enumerate flawed

### ISSUE THREAD

**Issue by bec65** [motoz/PellMon#102]
Pellmon v0.7.1-alpha3, MGM comfort lux

Trying to get the bitmask feature to work, but with no success.

mgm.conf looks like:
```
i33_item = in8
i33_data = INFLAG2
i33_longname = Input 08
i33_bitmask = 16
i33_tags = All Sensors
i33_enumeration =  in8
```

So - when looking at status.xml, the INFLAG2 has a value of 55 decimal
`<INFLAG2>55</INFLAG2>`

MGM web js ( TCNET II ) tells me that:

```
INFLAG2 = getXMLValue(a, " INFLAG2 ");
 setVal(" in8 ", (INFLAG2 & 16) ? " ON " : " OFF ");
 setVal(" in9 ", (INFLAG2 & 64) ? " ON " : " OFF ");
 setVal(" in10 ", (INFLAG2 & 128) ? " ON " : " OFF ");
 setVal(" in11 ", (INFLAG2 & 8) ? " ON " : " OFF ");
```

Looking at the value of in8, it shows:

> Input 08    16

However, trying to enumerate, I have to use "in8_enum_55" to get a correct enumeration, which somehow isn't logical.
I would have thoughe that "in8_enum_0" together with "in8_enum_1" should do, maybe even a "in8_enum_16" to match the bitmask/decimal

```
in8_enum_0 = OFF
in8_enum_1 = ON1 <<== Not Working
in8_enum_16 = ON16 <<== Not Working
in8_enum_55 = ON55 <<== Working
```

...so somehow the bitmask logic is flawed here - or my brain is :-)

..but thanks for a great application :-)

**Comment by motoz** [comment]
..Trying to remember what I did here... Seems you can't combine bitmasks with an enumeration. If you have an enumeration then it ignores the bitmask. See here (else if...) https://github.com/motoz/PellMon/blob/c4af95a6f353408d578cb9ea673befdb72264b5d/src/Pellmonsrv/plugins/mgm/__init__.py#L116

To make use of all flags in INFLAG2 you need to define one item for each bit like this: 

```
i33_item = in8
i33_data = INFLAG2
i33_longname = Input 08
i33_bitmask = 16
i33_tags = All Sensors

i34_item = in9
i34_data = INFLAG2
i34_longname = Input 09
i34_bitmask = 64
i34_tags = All Sensors
```

and so on...

Now all these items read as '1' or '0', which I suppose you would like to 'enumerate' as 'ON' and 'OFF'. Sadly the current code doesn't allow that, pull requests are allowed... :-)

**Comment by bec65** [comment]
Been there - done multiple variables. They all return the correct bitmasked AND, but the enumeration is on the INFLAG2 raw value :-(

**Comment by motoz** [comment]
Yes, the bitmask is not used at all if you have an enumeration, see the linked code.

**Comment by motoz** [comment]
You can use the 'calculate' plugin to convert the numbers into strings if you really want that.

**Comment by bec65** [comment]
Hmm - calculate might be a way..
Just saw the "bitmask" option and thought it would be the holy grail when getting on/off settings of a single variable.

Unfortunately, python isn't my strongest ( read: non existent ), so won't try to do a pull for now..

**Comment by motoz** [comment]
Well I suppose nothing really prevents allowing an enumeration to a bitmasked item, I just didn't do it that way. The whole MGM plugin was done rather quickly on request from a user who asked nicely, but then he disappeared so I lost interest. Very nice that you found some use for it anyway!

The calculate plugin is a sort of primitive stack machine. Basically you need to create a 'readitem' that contains a 'get' for the item you want to convert and a conditional expression that checks the value and leaves a different string on the stack depending on the value read. The value left on the stack after executing the 'script' is the returned when reading from the 'readitem'.
https://github.com/motoz/PellMon/blob/master/src/conf.d/plugins/calculate.conf

01_readitem = in8_text
01_prog = in8 get ON OFF ? 

assuming in8 contains zero or one, in8_text will then read as OFF or ON

**Comment by bec65** [comment]
Hi
Well - getting new "hardware" isn't going to work without "software", so found Pellmon when looking for solutions. :-)
The "build in" interface is ok, but just that, so for quick look it's fine..
Now it just needs to be tweaked to needs - especially as the TCNET II controller has the information to collect from..

I was looking briefly at calculate yesterday and played around with exact the two lines you mention - just other labels, but couldn't get it to work properly - I assumed an error 40
This example will not work. This was also my assumption using bitmask initially - returning boolean 0 or 1, but here it's more likely to be "0 or 16" - based on js-code from controller if doing similar "bitmask = " in mgm.conf and showing value in Pellmon.

```
setVal(" in8 ", (INFLAG2 & 16) ? " ON " : " OFF ");
setVal(" in9 ", (INFLAG2 & 64) ? " ON " : " OFF ");
setVal(" in10 ", (INFLAG2 & 128) ? " ON " : " OFF ");
setVal(" in11 ", (INFLAG2 & 8) ? " ON " : " OFF ");

```
Looking af TCNET controller, the actual value is
IN8: ON

Pellmon shows:

> Text 08    error

so"in8 get ON OFF ?" returns error - if I have understood syntax / config correct.
Tried with in9 - currently OFF, but same result.

Did copy & paste to avoid typo.
```
01_readitem = in8_text
01_prog = in8 get ON OFF ?
02_readitem = in9_text
02_prog = in9 get ON OFF ?

```
Assuming that the readout-sequence should look like:
```
i133_item = in8_bool
i133_data = in8_text
i133_longname = Text 08
i133_tags = All Sensors
```

Will try to dig into it tonight - if time permits.

**Comment by motoz** [comment]
I get the feeling that the mgm plugin and calculate plugin get mixed up here. Can you read the flags without errors using only the items created in the mgm plugin (in8, in9 and so on)?

When you have a working item that reads out the flag from the controller, you can create another item using 'calculate' that executes a script when read. In my example this item is called in8_text. It is created by the calculate plugin and it is found under the 'Calculate' submenu (there is no support for adding tags in the calculate plugin to make it show up anywhere else that I remember...).

The xxx_data in mgm.conf refers to an xml tag in the file that is polled from the controller, so this does not make sense:

> i133_data = in8_text

**Comment by bec65** [comment]
Obviously missed the "calculate submenu" part - might have been to focused on the other sub menus, trying to get values shown - and calculate.conf wasn't populated with entries earlier, so menu now showing up  :-)
But, yes - the mgm.conf works, letting me get the values of INFLAG2, but let me try to boil it down to the "in8" part.

mgm.conf:
```
i33_item = in8
i33_data = INFLAG2
i33_longname = Input 08
i33_bitmask = 16
i33_tags = All Sensors
```

With bitmask set, it in8 becomes 16, without bitmask, it get the INFLAG2 value

calculate.conf:
```
01_readitem = in8_text
01_prog = in8 get ON OFF ?
```

That's shown up in calculate submenu as
```
in8_Text    ON
```
So Calculate submenu works - bitmask ON:OFF shows up using calculate. Adding in9 etc shows similar pattern.

Time to play a little more with configs - maybe adding proper names and rearrange mgm.conf  :-)

**Comment by motoz** [comment]
Great!

> With bitmask set, it in8 becomes 16

Yes you are right... I just "assumed" a had converted it to 1/0 without actually checking what kind of code I wrote back then. But when thinking about it it kind of makes sense, if only it could be combined with an enumeration. Maybe I'll have a look at it at some point.

Let me know if you come up with a better mgm.conf, the quickly hacked up default can surely see some improvement.

**Comment by bec65** [comment]
Will try to polish up a mgm.conf - based on TCNET II status.xml and the corresponding js-code. Just has to decipher everything :-)

```
<response>
<T1>35</T1>
<T2>-128</T2>
<T3>-128</T3>
<T4>-128</T4>
<T5>-128</T5>
<TB>32</TB>
<TC>34</TC>
<ACCS>0</ACCS>
<OXY>665</OXY>
<INFLAG1>31</INFLAG1>
<INFLAG2>63</INFLAG2>
<FANRPM>0</FANRPM>
<OUTFLAG>0</OUTFLAG>
<MAF1>129</MAF1>
<MAF2>0</MAF2>
<FAN1>255</FAN1>
<FAN2>0</FAN2>
<RATED_POWER>124</RATED_POWER>
<PROC_ID>0</PROC_ID>
<MAF1_SP>226</MAF1_SP>
<MAF2_SP>-16532</MAF2_SP>
<OERR>-1</OERR>
<FERR>-1</FERR>
<TOERR>-1</TOERR>
<BCCERR>-1</BCCERR>
<ERRF1>0</ERRF1>
<ERRF2>0</ERRF2>
<AOXY>108</AOXY>
<RTM>0</RTM>
<M1P>0</M1P>
<M2P>0</M2P>
</response>
```


I was also assuming bitmask returning 1/0, so that confused me - together with the enumeration OR bitmask but not both.
You are right about the part of bitmask making sense - which also was my initial thought on how bitmask worked. 
An idea could be to either create a dedicated bitmask_enum = [0|1] in the bitmask part of code, or allow enumeration of [0|1] in that part...

**Comment by motoz** [comment]
I made a change in the develop branch to allow for both bitmask and enumeration, see the commit msg for an example how to use.

**Comment by bec65** [comment]
So - got a chance to play with new bitmask feature, but - now it don't cast any errors, but shows the bitmask value. Might have to go over the mgm.conf again, but initially no errors.

Based on commit msg example/style, the mgm.conf is changed to:

```
i33_item = in8
i33_data = INFLAG2
i33_longname = Room sensor
i33_description = Room heating demand
i33_bitmask = 16
i33_tags = All Sensors
i33_enum = inflag2

```
with enum config

```
inflag2_enum_0 = Off
inflag2_enum_1 = ON1
inflag2_enum_2 = ON2
inflag2_enum_4 = ON3
inflag2_enum_8 = ON4
inflag2_enum_16 = Activated
inflag2_enum_32 = ON6
inflag2_enum_64 = ON7
```

Shows:

> Room sensor   16
> 
> ID: in8
> Room heating demand

Something is not enumeration all the way

**Comment by motoz** [comment]
Took a while to spot it, it's the enum*eration*

i33_enum = inflag2
->
i33_enumeration = inflag2

It *should* work, I actually tested it before committing... :-)

**Comment by bec65** [comment]
Damn - you are right :-)

So much for copy & paste ( or reuse ) - didn't spot that one. Might have been to focused on the enum-section..

Did a quick config change & restart. Enumeration worked - tnx :-)

...so back to configuration cleanup :-)
