### ISSUE TITLE
PellmonMQTT - line 66 print 'Publish %s to pellmon/%s'%(value, item['name'])

### ISSUE THREAD

**Issue by lindberg87** [motoz/PellMon#109]
Hey 

I got this error with the script: File "pellmonMQTT.py", line 66 print 'Publish %s to pellmon/%s'%(value, item['name'])

What do I need to change on line 66 ?

Best Regards Stig.

**Comment by motoz** [comment]
That can hardly be the whole error, please post the whole error. Btw you are posting a PellmonMQTT issue under PellMon...

**Comment by lindberg87** [comment]
Sorry I move the thread to the pellmqtt area.
