### ISSUE TITLE
Reset silo level from HomeAssisent?

### ISSUE THREAD

**Issue by Nomisdk86** [motoz/PellMon#122]
Hi

Is there any way to run a command / MQTT message that will reset the silo level?
(so i dont have to go into Pellmon website)

Thanks for a great product :)

(Would be great also if it got updated to work on Debian 10/11)

**Comment by motoz** [comment]
Yes, you can use pellmoncli, e.g:

    pellmoncli set silo_reset_level 200

Or its interactive mode, where you have tab completion of commands and parameters:

    $ pellmoncli i
    >set silo_reset_level 100

Settings are mapped to mqtt (in pellmonmqtt) under pellmon/settings/item, so write to pellmon/settings/silo_reset_level
Writing to silo_reset_level will automatically set silo_reset_time to "now", you can also write the time later if you want to.

(Yes it would be great...)

**Comment by Nomisdk86** [comment]
Thanks, got it working with pellmoncli and remote ssh command from HA :)
