### ISSUE TITLE
Git flow

### ISSUE THREAD

**Issue by motoz** [motoz/PellMon#36]
I pushed a develop branch, but then I got a pull request to master and it fell out of use quickly... Seems it's the pull request submitter that decides where it is merged? 

Anyway, how do we do this in practice? Do we still use github pull requsts from forks or do all contributors push feature branches directly to this repo?

**Comment by JoakimSoderberg** [comment]
You can set the develop branch as the main branch under the repository settings, then any pull request will default towards that, and it will be the branch shown by default on github.

**Comment by motoz** [comment]
I suppose that would work, but then again pull requests are quite few and far between so it's not really a problem. Having the develop branch shown by default could lead to 'normal users' downloading the develop branch by mistake, which is worse than me having to merge the occasional pull request manually.
