### ISSUE TITLE
How to show a dynamic text string in the system display?

### ISSUE THREAD

**Issue by jteg68** [motoz/PellMon#63]
In a screen dump of the default system display there is a 'status OK' string. How is it done? Using the alarmXXX_YYY parts I've only managed to get a 1 or 0 or the whole "OK|FAIL" string but never a single OK or FAIL.

**Comment by motoz** [comment]
It's the 'alarm' parameter from scottecom or pelletcalc.

The status parameters in the 'Customalarms' plugin is zero or one:
 ```xxx_status = item to hold the result of the comparision, 1=True, 0=False```

The texts defined in the enum parameter is used when writing to the event log and sending mail.
``` xxx_enum = FalseText|TrueText```

You can use 'calculate' to convert the status to a string for displaying, here the item 'alarm_text' reads 'ALARM' or 'OK' and can be added to the system image with a text tagged 'paramname:alarm_text':

```
[plugin_customalarms]
a1_item = boiler_temp
a1_comparator = >
a1_level = 90
a1_status = boiler_temp_supervision

[plugin_caluclate]
c1_prog = if a1_status get then ALARM else OK end
c1_readitem = alarm_text
```
