### ISSUE TITLE
pellmonweb - make paths relative

### ISSUE THREAD

**Issue by osos** [motoz/PellMon#68]
I am running the pellmon on a raspberry pi.

However, I want to proxy the web interface through apache2 on my local webserver.

setting up like this:

    ProxyPass "/pellmon/" "http://192.168.1.123:8081/"
    ProxyReversePass "/pellmon/" "http://192.168.1.123:8081/"

Making accessible from the internet through http:/mydomain.tld/pellmon/

But the media files etc are not with relevative path and want to find http:/mydomain.tld/media/... instead of http:/mydomain.tld/pellmon/media/...

Please advise

**Comment by motoz** [comment]
I'm not very good at apache configuration but I have a working reverse proxy setup myself, as documented in https://github.com/motoz/PellMon/wiki/Reverse-proxy-with-authentication-on-apache2

Does that work for you? The code can surely be improved and pull requests are more than welcome...

**Comment by osos** [comment]
Thanks. The configuration of pellmonweb did the trick

    webroot = /pellmon
