### ISSUE TITLE
How show indoor temperatur

### ISSUE THREAD

**Issue by LaustL** [motoz/PellMon#74]
I have a Scotte / woody pellet burner, how do I show the indoor temperature on the front page just as the outdoor temperature.

Thanks in advance

with best regards
Laust Laursen

**Comment by motoz** [comment]
The 'indoor temperature' parameter is already shown in all of the included system images, but the parameter does not exist in controllers older than 6.03 (as far as I know). According to the manual http://nbe.dk/wp-content/uploads/2015/08/6.14-woody.pdf the sensor should be connected to input T6.

If you have an older controller that does not have an input for indoor temperature you can connect one (or several) onewire temperature sensors (eg. DS1820) by using a onewire adapter like eg. DS9490 and the pellmon plugin 'OWFS'.

**Comment by LaustL** [comment]
I am using a onewire sensor DS1820 but i can not get the temperatur from this on the system images?



best regards


Laust

________________________________
Fra: Anders Nylund <notifications@github.com>
Sendt: 28. februar 2017 09:47:43
Til: motoz/PellMon
Cc: LaustL; Author
Emne: Re: [motoz/PellMon] How show indoor temperatur (#74)


The 'indoor temperature' parameter is already shown in all of the included system images, but the parameter does not exist in controllers older than 6.03 (as far as I know). According to the manual http://nbe.dk/wp-content/uploads/2015/08/6.14-woody.pdf the sensor should be connected to input T6.

If you have an older controller that does not have an input for indoor temperature you can connect one (or several) onewire temperature sensors (eg. DS1820) by using a onewire adapter like eg. DS9490 and the pellmon plugin 'OWFS'.

**Comment by motoz** [comment]
See https://github.com/motoz/PellMon/wiki/Custom-system-image for info about getting data into the system image. The default images all include an indoor temperature text that is tagged with `paramname:indoor_temp`, which means that it will show the value of an _item_ with ID `indoor_temp`.

Either you modify the included system image to show the value from your own indoor temp item, or you name that item `indoor_temp` in your OWFS config. Note that the _scotteCom_ plugin also creates an item named `indoor_temp` (if your chip version is 6.03 or newer), in that case the OWFS plugin must be enabled after scotteCom (in the [enabled_plugins] section) to get what you want. When there are several items are created with the same ID, the one last created is the one that is used.
