### ISSUE TITLE
Cannot change system image 

### ISSUE THREAD

**Issue by lassepc** [motoz/PellMon#75]
Hi
I've installed the 0.7.0~beta7 on a fresh RPi 3.
When i change the systemimage in the webinterface.conf the shown systemimage is still the default system.svg
changing the row order for widgets work, so it updates the conf correctly.

I've even tried manually renaming the .svg files in /usr/share/Pellmonweb/media/img
and also pointing to a file in /home
but no luck, even with reboot, restart, force_reload..

Am i doing something wrong?
I have not tried the non-beta version.

Lasse

**Comment by motoz** [comment]
Most probably it's your web browser that isn't reloading the new image, instead just showing the old image it still has in it's cache. You need to force it to reload the page to retrieve the new system image, in many browsers (eg. firefox and chrome) that's control+F5.

**Comment by lassepc** [comment]
Seems Chrome was the problem as you guessed. Even though refreshing the page was not enough nor rebooting the devices.

The image now updated after clearing the browser cache. 

Had to do this on both the RPi and my android phone, before they all showed the new image.
(Both running Chrome)

**Comment by motoz** [comment]
Seems as chrome is getting more and more aggressive in it's caching behavior. I suppose it's best to fix it in pellmon since this is not the first time this has come up.
