### ISSUE TITLE
consumption data is missing after power off.

### ISSUE THREAD

**Issue by Heltzen** [motoz/PellMon#77]
Hi running peloton on raspberry, with a ramdisk for the rrd database. 
We have som garten lighting there some times cut the power to the whole house. I have notised that the consumption data is missing and the silo level off after a power shortage.

Dit i set something op wrong?

**Comment by motoz** [comment]
If you set up the ramdisk according to the guide in the wiki https://github.com/motoz/PellMon/wiki/How-to-set-up-ramdisk-for-the-rrd-database-on-a-Rasperry-Pi the database is written to the sd card every second hour, which means that after a reboot you will be missing up to two hour of data. The interval can be adjusted with the config option *db_store_interval* in https://github.com/motoz/PellMon/blob/master/src/conf.d/database.conf.in#L64

If everything is gone after a power out, then there is something wrong. If that's the case, can you provide some more details of what's happening and how you have configured it?

**Comment by Heltzen** [comment]
Hi Anders 

I have tried to follow the guide several times, pellmon is working perfect until i restart the pie or there is a powerdrop. 

Here is my config file regards the database

[conf]
# Full path to the rrd database
# If the file does not exist it is created when pellmonsrv starts
database = /mnt/ramdisk/rrd.db

# Full path to the optional persistent rrd database. It is copied
# over the database file at startup, and on shutdown the database
# is copied to the persistent_db file. Useful if the database
# is in a ramdisk
persistent_db = /var/lib/pellmon/nvrrd.db

# If persistent_db is in use the database is copied to
# persistent_db every db_store_interval seconds
db_store_interval = 7200

# rrd database update interval in seconds
pollinterval = 30


The Ramdisk is mounted and seams to work as there is data on the disk.

pi@raspberrypi:~ $ df -h
Filsystem      Størr Brugt  Tilb Brug% Monteret på
/dev/root       7,3G  3,8G  3,1G   55% /
devtmpfs        459M     0  459M    0% /dev
tmpfs           463M   38M  426M    9% /dev/shm
tmpfs           463M  6,3M  457M    2% /run
tmpfs           5,0M  4,0K  5,0M    1% /run/lock
tmpfs           463M     0  463M    0% /sys/fs/cgroup
tempfs           20M   11M  9,0M   55% /mnt/ramdisk
/dev/mmcblk0p1   41M   21M   21M   51% /boot
tmpfs            93M     0   93M    0% /run/user/1000
pi@raspberrypi:~ $ 

I just tried to reboot the raspberry and it is the same result.
Silo level goes to 401 kg, consumption data is missing and the historik data "the graf" is missing. Se picture.   

Regards
	Jesper Heltzen

**Comment by motoz** [comment]
That's strange, I don't see anything wrong with that part of the configuration. Do you get an line in your event log saying that it has recreated the rrd database every time you restart? If you don't get that, then you have a valid database in /var/lib/pellmon/nvrrd.db, but for some reason pellmonsrv fails to update it. What's the output of:

    ls -l /var/lib/pellmon

Should look like:

    -rw-r--r-- 1 pellmonsrv nogroup  8327768 Aug 20 17:17 nvrrd.db

(the picture is missing)

**Comment by Heltzen** [comment]
Here is my output from

ls -l /var/lib/pellmon

totalt 22532
-rw-r--r-- 1 root       root    11530528 jun  6 13:54 nvrrd.db
-rw-r--r-- 1 pellmonsrv nogroup     3072 jun  6 13:54 pellmon_settings.db
-rw-r--r-- 1 pellmonsrv nogroup 11530528 jun  6 14:07 rrd.db

In the picture is the log fore a restart 

Besdt regards
	Jesper Heltzen

**Comment by motoz** [comment]
There are no pictures here!

Anyway, nvrrd.db is owned by root, so pellmonsrv can't write to it. You can fix that with:

    sudo chown pellmonsrv /var/lib/pellmon/nvrrd.db

**Comment by Heltzen** [comment]
Thanks it seams to work, the data is now saved on the pie.

Is it possible to get the hot water boiler on the graph so i can follow the curve in the hot water tank on the graph?

**Comment by motoz** [comment]
Great!

Yes of course, just add the ID for the hot water parameter to the [pollvalues] section in database.conf. You can find the correct ID from the parameters view in the web interface by clicking on the data you want to add.

**Comment by Heltzen** [comment]
Thanks it seams to work.

Med venlig hilsen
	Jesper Heltzen
