### ISSUE TITLE
OneWire

### ISSUE THREAD

**Issue by japlab** [motoz/PellMon#86]
Hi. I'm up and running on a RPI v3 with Raspbian. 
I am not a expert on Linux and need help with connecting DS18B20 to the database.
The sensor respond when I poll the adress like: 

> pi@raspberrypi:/sys/bus/w1/devices/28-041753710fff $ cat w1_slave
> 98 01 4b 46 7f ff 0c 10 19 : crc=19 YES
> 98 01 4b 46 7f ff 0c 10 19 t=25500

The log file show:
> 2017-12-13 20:50:38,679 - INFO - Activated plugins: ScotteCom, SiloLevel, Consumption, Cleaning, Onewire
> 2017-12-13 21:04:42,077 - INFO - stop
> 2017-12-13 21:04:42,078 - INFO - deactivated ScotteCom
> 2017-12-13 21:04:42,079 - INFO - deactivated SiloLevel
> 2017-12-13 21:04:42,081 - INFO - deactivated Consumption
> 2017-12-13 21:04:42,082 - INFO - deactivated Cleaning
> 2017-12-13 21:04:42,083 - INFO - deactivated Onewire
> 2017-12-13 21:04:42,990 - INFO - Unreadable config files: /etc/pellmon/conf.d/webinterface.conf, /etc/pellmon/conf.d/enabled_plugins.conf, /etc/pellmon/conf.d/plugins/onewire.conf
> 2017-12-13 21:04:42,995 - INFO - invalid setting for plugin_dirs
> 2017-12-13 21:04:43,017 - INFO - starting PellMon
> 2017-12-13 21:04:43,018 - INFO - Looking for plugins in /usr/lib/python2.7/dist-packages/Pellmonsrv/plugins
> 2017-12-13 21:04:43,244 - INFO - serial port ok
> 2017-12-13 21:04:43,320 - INFO - chip version detected as: 4.99F
> 2017-12-13 21:04:43,339 - INFO - Activated plugins: ScotteCom, SiloLevel, Consumption, Cleaning, Onewire

May be a problem with the path or permissions.!
Anyway, nice program, I love it. Kind regards Jan

[my setupchair](https://www.icloud.com/sharedalbum/da-dk/#B0QGI9HKKGCgXJm)

**Comment by motoz** [comment]
`Unreadable config files: /etc/pellmon/conf.d/webinterface.conf, /etc/pellmon/conf.d/enabled_plugins.conf, /etc/pellmon/conf.d/plugins/onewire.conf`

There is probably some kind of error in those three config file that prevents the config parser from understanding the file contents. Check that every line either is empty, starts with a `#`, is in the form `single_word = something` or is a `[sectionname]`.

For instance, if you by mistake remove the starting `#` from one existing comment then it can't parse the contents.

Post the complete contents of one of the files if you don't spot the errror.

Nice 'setupchair', looks like you spend a lot of quality time there... :-)

**Comment by japlab** [comment]
Found a "space before # " in the onewire.conf file and one more typing error in a file I don't remember.
The sensor read fine and show up in the web frontend. 
I have one last error I can't adress in plugin_dirs:

> 2017-12-14 17:05:51,921 - INFO - stop
> 2017-12-14 17:05:51,922 - INFO - deactivated ScotteCom
> 2017-12-14 17:05:51,935 - INFO - deactivated RaspberryGPIO
> 2017-12-14 17:05:51,936 - INFO - deactivated SiloLevel
> 2017-12-14 17:05:51,937 - INFO - deactivated Consumption
> 2017-12-14 17:05:51,939 - INFO - deactivated Cleaning
> 2017-12-14 17:05:51,940 - INFO - deactivated Onewire
> 2017-12-14 17:05:52,786 - INFO - invalid setting for plugin_dirs
> 2017-12-14 17:05:52,802 - INFO - starting PellMon
> 2017-12-14 17:05:52,808 - INFO - Looking for plugins in /usr/lib/python2.7/dist-packages/Pellmonsrv/plugins
> 2017-12-14 17:05:53,025 - INFO - serial port ok
> 2017-12-14 17:05:53,100 - INFO - chip version detected as: 4.99F
> 2017-12-14 17:05:53,133 - INFO - Activated plugins: ScotteCom, RaspberryGPIO, SiloLevel, Consumption, Cleaning, Onewire

Only reference to "plugin_dirs" I find in "enabled_plugin" but can't adress any error.

update to setupchair.
Yes, I relax and have a great time doing this ;-) and thank you so much for quick response, excellent.

**Comment by motoz** [comment]
You can forget about that warning, it's just complaining that the setting 'plugin_dirs' is not a valid list of directories, which it of course isn't since it doesn't exist... It's actually a bug, the setting 'plugin_dirs' is completely optional so it shouldn't complain when it doesn't exist. But luckily it's harmless except for the noise in the log.
