### ISSUE TITLE
Connecting to EDS ow-server-enet-2

### ISSUE THREAD

**Issue by Flygarkatt** [motoz/PellMon#99]
Hi,
Need the correct syntax for connecting 1-wire over ethernet.

owfs.conf states the following:
# xxx_item = item name for the owfs sensor value
# xxx_path = [server::]path[:port], default server:port is localhost:4304

Reading from owserver i get ROMID: 2F000007E4C43428

Please clarify syntax for a mechanical engineer ;-)

/Bqt

**Comment by motoz** [comment]
If you have your owserver running on the same machine as pellmon then you can skip the server part, and if you haven't changed the default port in owserver then you can skip the port part also. When the owserver is on another computer you add the ip address or hostname for that computer. If it is running on a linux computer you can probably use the hostname.local form (zeroconf multicast dns stuff) to access it. 

Say the hostname of the owserver computer is 'myowserver' then you use something like (from my own temperature sensor config):

ow1_path = myowserver.local::28.515338050000/temperature 
or
ow1_path = 192.18.0.12::28.515338050000/temperature

Note that owserver by default doesn't allow you to connect from another computer so you have to configure it to allow that (if I remember correctly).

**Comment by motoz** [comment]
Ok now I get it (didn't read the headline before, only the body text of the question). So you don't actually have an "owserver" running (the open source server from the https://owfs.org/ project, that is). EDS ow-server-enet-2 seems to be some kind of hardware speaking it's own protocol, pellmon has no support for that. 

If you are into programming then adding support for it would not be much work, look into the wiki example https://github.com/motoz/PellMon/wiki/Make-your-own-plugin,-pushover.net-example for some pointers.
